#spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=testing;encrypt=false;
#
#spring.datasource.username=huzaifa
#spring.datasource.password=fast123
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.hibernate.ddl-auto=create
##spring.jpa.show-sql=true
#spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect




spring.datasource.url=jdbc:sqlserver://healthlink-fyp.database.windows.net:1433;database=testing;user=huzaifa@healthlink-fyp;password=Fast1234;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update

server.port=443

server.error.include-message=always

spring.devtools.restart.enabled=true



